### PR TITLE
Remove updateAdverts

### PR DESCRIPTION
**Pull request by webb04**
Max suggested reusing insertAdverts for updating ad positions. Would this also work on iOS?

### CODE REVIEW

**Comment by maxspencer** [comment]
Could we also ad an `id` of type `String` to the `AdSlot` model as part of this PR?

**Comment by webb04** [comment]
We can do, I thought iOS was able to able to implement ads without the use of IDs and metadata? Although I may have just been seeing test ads. @faresite

**Comment by maxspencer** [comment]
> We can do, I thought iOS was able to able to implement ads without the use of IDs and metadata? Although I may have just been seeing test ads. @faresite

That's interesting, our existing implementation seems to use the `ArticleItem` quite extensively when making requests for ads.

My request for an `id` on the `AdSlot` isn't actually to do with loading the real ads though. It would just be handy to have unique `id`s for each slot to make the code for updating existing ad slots simpler. The id's can just be UUIDs or like "ad-slot-1" etc.

**Comment by webb04** [comment]
Closing as this would require a bit of refactoring for iOS.

**Pull request closed without merging**
