### PR TITLE
Has seen article

### PR DESCRIPTION
**Pull request by webb04**
## What does this change?
Adds the ability to query whether a user has read an article or list of articles before

### CODE REVIEW

**Review by JamieB-gu — COMMENTED** [review]
Nice! Couple questions:

1. Do we to ask the native layers to implement both? Can we implement `hasSeenArticle` on our side in terms of `hasSeenArticles`:

```ts
const hasSeenArticle = (id: string): boolean => user.hasSeenArticles([id]);
```

2. Is `hasSeenArticles` an "any" or an "all"? As in, does it return `true` only if the user has seen *all* the articles in the list, or does it return `true` as long as they have seen *at least one* of the articles in the list? Under what circumstances is it used?

**Comment by webb04** [comment]
I think it makes sense to just have the one API for a list of articles and we can add that our side to pass through a list.

I updated it to return a list of booleans, so it would report back if a user has seen each one. We could add more structure and have a return type:

`
{
  id: "news",
  hasSeen: true
}
`

**Comment by JamieB-gu** [comment]
> We could add more structure and have a return type

Yeah sounds sensible, I guess it depends on how you're planning to use it. You could also treat it like a filter and have it return the subset of articles that have been read. E.g.:

```thrift
list<string> filterSeenArticles(1:list<string> articleIds)
```

**Comment by webb04** [comment]
I'm happy to treat it as a filter, not sure if either would be easier for the clients? @faresite @maxspencer

**Review by maxspencer — APPROVED** [review]
Happy to do what you think is best, it's all much of a muchness in terms of implementation from my point of view.

**Review by JamieB-gu — APPROVED** [review]

**Pull request merged**
