### PR TITLE
Use `async_servers` generator option

### PR DESCRIPTION
**Pull request by alexanderedge**
This will allow the webview to ask the native layer to perform asynchronous activities such as following / unfollowing a topic.

I've also added output directory option to avoid the copy step.

### CODE REVIEW

**Comment by alexanderedge** [comment]
I'm now doubting if I actually have this right – it's the webview that needs to call the native layer asynchronously, and I'm not sure how that works using `async_clients`.

**Comment by alexanderedge** [comment]
> I'm now doubting if I actually have this right – it's the webview that needs to call the native layer asynchronously, and I'm not sure how that works using `async_clients`.

No, this is correct.

**Comment by alexanderedge** [comment]
@davidfurey did you use `async_clients` generator option for https://github.com/guardian/ios-live/pull/4758?

**Comment by alexanderedge** [comment]
Follow-up question for @davidfurey, do you recall having to make `CalculatorProcessorAsync` based on `CalculatorProcessor` yourself, or was it generated? I'm seeing that running `thrift` will create `Native`, `NativeAsync`, `NativeProcessor` but mysteriously no `NativeAsyncProcessor` or `NativeProcessorAsync`

**Comment by davidfurey** [comment]
> Follow-up question for @davidfurey, do you recall having to make `CalculatorProcessorAsync` based on `CalculatorProcessor` yourself, or was it generated? I'm seeing that running `thrift` will create `Native`, `NativeAsync`, `NativeProcessor` but mysteriously no `NativeProcessorAsync`.
> 
> [This](https://github.com/guardian/ios-live/pull/4758/commits/45dc65693106e6da8bead8cff1d827c81d9ce9c3) looks like the commit where async functionality was added.

You need to run `thrift --gen swift:async` to create the async processor.

You can choose whether the iOS code responds sync or async by implementing `NativeProcessor` or `NativeProcessorAsync`.  Sync makes the code a bit easier to read, but if you are doing a network request or something like that, async might be more appropriate.  But either way, when the webview calls the native layer, the response will always be async (from the webview's point of view), because of the underlying communication mechanism between webview<-->native.

**Comment by alexanderedge** [comment]
> > Follow-up question for @davidfurey, do you recall having to make `CalculatorProcessorAsync` based on `CalculatorProcessor` yourself, or was it generated? I'm seeing that running `thrift` will create `Native`, `NativeAsync`, `NativeProcessor` but mysteriously no `NativeProcessorAsync`.
> > [This](https://github.com/guardian/ios-live/pull/4758/commits/45dc65693106e6da8bead8cff1d827c81d9ce9c3) looks like the commit where async functionality was added.
> 
> You need to run `thrift --gen swift:async` to create the async processor.
> 
> You can choose whether the iOS code responds sync or async by implementing `NativeProcessor` or `NativeProcessorAsync`. Sync makes the code a bit easier to read, but if you are doing a network request or something like that, async might be more appropriate. But either way, when the webview calls the native layer, the response will always be async (from the webview's point of view), because of the underlying communication mechanism between webview<-->native.

Thanks a lot, I'll update this PR. Even though some functions could appear synchronous as far as the native layer is concerned, I think using the async interface for all functions would be less complicated than using two interfaces with duplicated functions.

**Comment by alexanderedge** [comment]
Not yet – once David pushes his code to generate the async Swift interface then I'll make the changes in the app.

**Comment by alexanderedge** [comment]
[Here](https://github.com/apache/thrift/pull/1997) is the PR against Apache Thrift repo with the changes necessary to generate asynchronous servers.

**Pull request closed without merging**
