### PR TITLE
remove unused webview thrift file

### PR DESCRIPTION
**Pull request by webb04**
With the new fontSize solution it looks like we no longer need the native to webView communication.

### CODE REVIEW

**Comment by JamieB-gu** [comment]
Agreed, but we should probably wait to confirm that the new solution actually works! We need iOS and Android changes to be sure.

**Comment by maxspencer** [comment]
I will try to find time to test out the `fontSize.css` thing today so we can make a call on this ASAP.

**Comment by webb04** [comment]
It seems like the `fontSize.css` tests were positive? @faresite @maxspencer

**Comment by alexduf** [comment]
🎉

**Pull request merged**
